version: '2'

services:

  # Build the container using the client Dockerfile
  client:
      build: ./client
      # This line maps the contents of the client folder into the container.
      volumes:
        - ./client:/usr/src/app

  # Build the container using the nginx Dockerfile
  nginx:
    build: ./nginx
    # Map Nginx port 80 to the local machine's port 80
    ports:
      - "80:80"
    # Link the client container so that Nginx will have access to it
    links:
      - client